# Generated by Django 5.1.7 on 2025-06-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_word', models.CharField(max_length=255)),
                ('time_processed', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text_size', models.IntegerField()),
            ],
        ),
    ]
