# Generated by Django 5.1.7 on 2025-06-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_main_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
