# Generated by Django 5.1.7 on 2025-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='collection_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
