# Generated by Django 5.1.7 on 2025-06-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_documents_collection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
